spring:
  application:
    name: SpringSecurityApplication
  datasource:
    url: jdbc:postgresql://localhost:5432/postgres
    username: postgres
    password: 12341234
    driver-class-name: org.postgresql.Driver
  driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: none # When you launch the application for the first time - switch "none" at "create"
    show-sql: true
    database: postgresql
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    open-in-view: false
    generate-ddl: true
    properties:
      hibernate:
        default_schema: registration